/**
 * Tool registry — wires up all tools for ListTools + CallTool handlers.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py.
 * To update, edit src/index.ts (existing tools) or sources.yml (meta-tools)
 * and re-run the helper.
 */

import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import type { Server } from "@modelcontextprotocol/sdk/server/index.js";

import { handleSearchGuidance, SEARCH_GUIDANCE_TOOL } from "./search-guidance.js";
import { handleGetGuidance, GET_GUIDANCE_TOOL } from "./get-guidance.js";
import { handleSearchAdvisories, SEARCH_ADVISORIES_TOOL } from "./search-advisories.js";
import { handleGetAdvisory, GET_ADVISORY_TOOL } from "./get-advisory.js";
import { handleListFrameworks, LIST_FRAMEWORKS_TOOL } from "./list-frameworks.js";

import { listSources } from "./list-sources.js";
import { about } from "./about.js";
import { checkDataFreshness } from "./check-data-freshness.js";

export const TOOLS = [
  SEARCH_GUIDANCE_TOOL,
  GET_GUIDANCE_TOOL,
  SEARCH_ADVISORIES_TOOL,
  GET_ADVISORY_TOOL,
  LIST_FRAMEWORKS_TOOL,
  {
    name: "list_sources",
    description:
      "List the authoritative data sources backing this MCP server, including coverage, licensing, and last-verified date per source. No arguments required.",
    inputSchema: { type: "object" as const, properties: {}, required: [] },
  },
  {
    name: "about",
    description:
      "Server identity, version, jurisdiction, source summary, and tool catalog. No arguments required.",
    inputSchema: { type: "object" as const, properties: {}, required: [] },
  },
  {
    name: "check_data_freshness",
    description:
      "Report per-source data age and flag staleness against a threshold (default 90 days). Use `source` to filter by name/authority substring; use `threshold_days` to override the staleness cutoff.",
    inputSchema: {
      type: "object" as const,
      properties: {
        source: {
          type: "string",
          description: "Optional substring to filter sources by name or authority.",
        },
        threshold_days: {
          type: "number",
          description: "Days after last_verified at which a source is considered stale. Default 90.",
        },
      },
      required: [],
    },
  },
];

export const TOOL_NAMES: readonly string[] = TOOLS.map((t) => t.name);

import { textContent, errorContent } from "./_helpers.js";

export function registerTools(server: Server): void {
  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: TOOLS,
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args = {} } = request.params;

    try {
      switch (name) {
        case "search_guidance":
          return await handleSearchGuidance(args);

        case "get_guidance":
          return await handleGetGuidance(args);

        case "search_advisories":
          return await handleSearchAdvisories(args);

        case "get_advisory":
          return await handleGetAdvisory(args);

        case "list_frameworks":
          return await handleListFrameworks(args);

        case "list_sources":
          return textContent(await listSources({} as never));

        case "about":
          return textContent(await about({} as never));

        case "check_data_freshness":
          return textContent(await checkDataFreshness(args as { source?: string; threshold_days?: number }));

        default:
          return errorContent(`Unknown tool: ${name}`);
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return errorContent(`Error in ${name}: ${message}`);
    }
  });
}

